<?php
/**
 * @package   jInbound
 * @contact   www.joomlashack.com, help@joomlashack.com
 * @copyright 2013-2015 Anything-Digital.com
 * @copyright 2016-2021 Joomlashack.com. All rights reserved
 * @license   http://www.gnu.org/licenses/gpl.html GNU/GPL
 *
 * This file is part of jInbound.
 *
 * jInbound is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 2 of the License, or
 * (at your option) any later version.
 *
 * jInbound is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with jInbound.  If not, see <http://www.gnu.org/licenses/>.
 */

defined('JPATH_PLATFORM') or die;

$this->cols = 12;

echo $this->loadTemplate('list');

?>

<script type="text/javascript">
    (function($) {
        $(function() {
            var ids = [];
            // autogenerated list
            <?php foreach ($this->items as $item) : ?>
            ids.push(<?php echo (int)$item->id; ?>);
            <?php endforeach; ?>
            if (ids.length) {
                $.ajax('../index.php?option=com_jinbound&task=landingpageurl&id[]=' + ids.join('&id[]='), {
                    dataType: 'json',
                    success : function(response) {
                        if (!response) {
                            return;
                        }
                        if (!(response.links && response.links.length)) {
                            if (response.id) {
                                var cell = $('#landingpagelink_' + response.id);
                                if (cell && response.sef) {
                                    cell.append($('<a href="' + response.sef + '" target="_blank" title="<?php echo JText::_('COM_JINBOUND_OPEN_IN_NEW_WINDOW'); ?>"><img src="../media/system/images/weblink.png" /></a>'));
                                }
                            }
                            return;
                        }
                        $.each(response.links, function(i, el) {
                            var cell = $('#landingpagelink_' + el.id);
                            if (cell && el.sef) {
                                cell.append($('<a href="' + el.sef + '" target="_blank" title="<?php echo JText::_('COM_JINBOUND_OPEN_IN_NEW_WINDOW'); ?>"><img src="../media/system/images/weblink.png" /></a>'));
                            }
                        });
                    }
                });
            }
        });
    })(jQuery);
</script>
